services:
  log-api:
    image: log-api
    build: ./logger/api/

  log-database:
    image: log-database
    build: ./logger/database

  search_engine:
    image: search-engine
    build: ./search_engine
